int *fctadd(int *str1,int *str2);
int *fctsubt(int *first, int *second);
int *fctminus(int *x,int *y);
int *fctmult(int *str1,int *str2);
int *fctdivd(int *str1,int *str2);
int *fctimul(int *str1,int *str2);
int *fctidiv(int *str1,int *str2);
int *fctmuli(int *str,int num) ;
int *fctdivi(int *str,int num);
int *intofs(int value);
int *dstofs(int *dstr);
int *dectof(int *decml);
int *fintod(int *fctin);
int *fcttod(int *factrl, int sigdgt);
